"""TrackScribe-owned process bridge to the installed REAPER ReaScript host."""

from __future__ import annotations

import argparse
import json
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Sequence

from trackscribe.errors import PipelineError
from trackscribe.reaper_discovery import find_reaper_executable
from trackscribe.reaper_midi import prepare_reaper_media
from trackscribe.reaper_artifacts import (
    ReaperArtifact,
    ReaperSelection,
    SkippedArtifact,
    collect_reaper_artifacts,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
COMMON_REASCRIPT = PROJECT_ROOT / "reaper" / "TrackScribe_Import.lua"


class ReaperBridgeError(PipelineError):
    """Raised when a safe REAPER import cannot be dispatched."""


@dataclass(frozen=True)
class ReaperDispatch:
    """Files and command accepted for one asynchronous REAPER dispatch."""

    project_dir: Path
    wrapper_path: Path
    command: tuple[str, ...]
    imported: tuple[ReaperArtifact, ...]
    skipped: tuple[SkippedArtifact, ...]


ProcessLauncher = Callable[..., object]


def _lua_string(value: str | Path) -> str:
    """Return a UTF-8 Lua string with forward slashes and escaped quotes."""

    text = Path(value).resolve().as_posix() if isinstance(value, Path) else value
    return json.dumps(text, ensure_ascii=False)


def write_project_wrapper(
    project_dir: str | Path,
    artifacts: Sequence[ReaperArtifact],
    *,
    common_script: Path = COMMON_REASCRIPT,
) -> Path:
    """Write the small project-specific transport consumed inside REAPER."""

    project = Path(project_dir).expanduser().resolve()
    wrapper = project / "reaper" / "import_to_reaper.lua"
    wrapper.parent.mkdir(parents=True, exist_ok=True)
    entries = ",\n".join(
        "    { path = %s, name = %s, media_type = %s }"
        % (
            _lua_string(artifact.path),
            _lua_string(artifact.track_name),
            _lua_string(artifact.media_type),
        )
        for artifact in artifacts
    )
    content = (
        "-- Generated by TrackScribe. Safe to regenerate.\n"
        f"local importer = dofile({_lua_string(common_script)})\n"
        "importer.import({\n"
        f"  project_dir = {_lua_string(project)},\n"
        f"  report_path = {_lua_string(wrapper.parent / 'import_result.tsv')},\n"
        "  artifacts = {\n"
        f"{entries}\n"
        "  }\n"
        "})\n"
    )
    wrapper.write_text(content, encoding="utf-8", newline="\n")
    return wrapper


def send_project_to_reaper(
    project_dir: str | Path,
    *,
    selection: ReaperSelection = ReaperSelection(),
    reaper_executable: str | Path | None = None,
    launcher: ProcessLauncher = subprocess.Popen,
) -> ReaperDispatch:
    """Validate outputs and dispatch one wrapper to a new safe project tab."""

    executable = find_reaper_executable(reaper_executable)
    if executable is None:
        raise ReaperBridgeError("REAPER executable not found. Configure reaper.exe first.")
    if not COMMON_REASCRIPT.is_file():
        raise ReaperBridgeError(f"TrackScribe ReaScript not found: {COMMON_REASCRIPT}")
    artifacts, skipped = collect_reaper_artifacts(project_dir, selection)
    if not artifacts:
        reasons = "; ".join(f"{item.key}: {item.reason}" for item in skipped)
        raise ReaperBridgeError(f"No non-empty selected artifacts to import ({reasons})")
    project = Path(project_dir).resolve()
    artifacts = prepare_reaper_media(project, artifacts)
    wrapper = write_project_wrapper(project, artifacts)
    command = (str(executable), "-nonewinst", str(wrapper))
    launcher(list(command), cwd=str(Path(project_dir).resolve()), shell=False)
    return ReaperDispatch(project, wrapper, command, artifacts, skipped)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Send a TrackScribe project to REAPER")
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--reaper", type=Path)
    for key in ("drums", "bass", "harmony", "vocals"):
        parser.add_argument(f"--{key}", action=argparse.BooleanOptionalAction, default=True)
    return parser


def main(argv: list[str] | None = None) -> int:
    """Dispatch from another environment and report one machine-readable line."""

    args = _parser().parse_args(argv)
    selection = ReaperSelection(args.drums, args.bass, args.harmony, args.vocals)
    try:
        result = send_project_to_reaper(
            args.project, selection=selection, reaper_executable=args.reaper
        )
    except Exception as exc:
        print(json.dumps({"type": "error", "message": str(exc)}, ensure_ascii=False))
        return 1
    print(
        json.dumps(
            {
                "type": "dispatched",
                "project": str(result.project_dir),
                "wrapper": str(result.wrapper_path),
                "imported": [item.key for item in result.imported],
                "skipped": [asdict(item) for item in result.skipped],
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
